name: Build & Deploy Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18   # 不使用 cache，避免找 lock 文件

      # 1) 非交互式脚手架（JavaScript）
      - name: Scaffold Docusaurus (non-interactive)
        run: |
          npx --yes create-docusaurus@latest site classic \
            --skip-install \
            --javascript \
            --package-manager npm \
            --yes
          cd site
          npm ci

      # 2) 把仓库根目录里的文档复制到 site/docs（保留目录结构）
      - name: Copy docs from repository root into site/docs
        run: |
          rm -rf site/docs
          mkdir -p site/docs
          rsync -av --prune-empty-dirs \
            --include='*/' \
            --include='*.md' --include='*.MD' --include='*.mdx' \
            --exclude='*' ./ site/docs/
          rsync -av --prune-empty-dirs \
            --include='*/' \
            --include='*.png' --include='*.jpg' --include='*.jpeg' --include='*.gif' --include='*.svg' \
            --include='*.pdf' --include='*.mp4' --include='*.webm' \
            --exclude='*' ./ site/docs/

      # 3) 最小化配置（自动注入 url/baseUrl）
      - name: Write docusaurus.config.js for Pages
        run: |
          REPO="${GITHUB_REPOSITORY#*/}"
          OWNER="${GITHUB_REPOSITORY_OWNER}"
          cat > site/docusaurus.config.js <<'EOF'
          import {themes as prismThemes} from 'prism-react-renderer';
          export default {
            title: 'Docs',
            url: 'https://GITHUB_OWNER.github.io',
            baseUrl: '/GITHUB_REPO/',
            organizationName: 'GITHUB_OWNER',
            projectName: 'GITHUB_REPO',
            trailingSlash: false,
            i18n: { defaultLocale: 'en', locales: ['en'] },
            presets: [
              ['@docusaurus/preset-classic',
                { docs: { sidebarPath: undefined }, blog: false, pages: false }
              ]
            ],
            themeConfig: {
              prism: { theme: prismThemes.github, darkTheme: prismThemes.dracula }
            }
          }
          EOF
          sed -i "s/GITHUB_OWNER/$OWNER/g" site/docusaurus.config.js
          sed -i "s/GITHUB_REPO/$REPO/g"  site/docusaurus.config.js

      # 4) 自动侧边栏
      - name: Force autogenerated sidebar
        run: |
          cat > site/sidebars.js <<'EOF'
          const sidebars = {
            tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
          };
          export default sidebars;
          EOF

      # 5) 构建
      - name: Build
        run: |
          cd site
          npm run build

      # 6) 交给 Pages 部署
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
